name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: psf/black@stable
      - name: Python Code Quality and Lint
      uses: ricardochaves/python-lint@v1.4.0
